### ISSUE TITLE
Error Code AADB2C / Message: Please Complete the Captcha / Status: 400

### ISSUE THREAD

**Issue by SilviuMihai** [Azure-Samples/active-directory-b2c-node-sign-up-user-flow-captcha#5]
Hello,

So I followed the steps from the description, by adding the html page and the azure function code in the http trigger.
After doing this, I go up to the Sign Up page, I complete it with the email than do the captcha and I get the check mark and after I press to create the account, but it doesn't go further and asks me to complete the captcha which is already completed.

I did look on the network to see the request and I see the following:
**Error Code: AADB2C
Message: Please complete the Captcha
Status: 400** 

_What is this ? 
Or where should I look into ? to figure it out where is the problem.
What to check more exactly ?_

I cannot figure it out where I missed something. 
Thank you
@nickgmicrosoft 
@mirkon90

**Comment by SilviuMihai** [comment]
After checking the logs in the portal azure function app, the message is from the function itself and it seems that when I press the create button (to create the user it's calling the api) and in the logs appears:
2022-11-10T10:14:45.118 [Information] JavaScript HTTP trigger function processed a request.
2022-11-10T10:14:45.118 [Information] value of captcha check
2022-11-10T10:14:45.119 [Information] undefined
2022-11-10T10:14:45.119 [Information] **No captcha token verification code was sent to the API.**
2022-11-10T10:14:45.120 [Information] Executed 'Function'
Means that is failing in the Azure Function, because the message is from the function, but I cannot figure it out how to make it work.

**Comment by mistermik** [comment]
Hello @SilviuMihai,
Make sure that there is no "-" in the b2c-extensions-app Application (client) ID that you add in the environment variable.
Example:
"B2C_EXTENSIONS_APP_ID":"02427953f9a647009a8f351234567890" 

and not 02427953-f9a6-4700-9a8f-351234567890
 
Thank you
_Michele_

**Comment by mistermik** [comment]
Hello @SilviuMihai,
Make sure that there is no "-" in the b2c-extensions-app Application (client) ID that you add in the environment variable.
Example:
"B2C_EXTENSIONS_APP_ID":"02427953f9a647009a8f351234567890"

and not 02427953-f9a6-4700-9a8f-351234567890
 
Thank you.

Michele

**Comment by SilviuMihai** [comment]
**Thank you @mistermik , that was it. Now it works.**

I want to add one thing, the page how they are describing to add the captcha, should be changed, to a more of a increasing progress, like:
step 1 - a) do this b) do this and so on, 
step 2 - a) do this b) do this and so on...
and of course where you can add information's in between always adds up for a better understanding.
That is my experience and what I think it would be an easier tutorial to follow.
Thank you again. (I will close the issue in the next 2 days, in case something will be added)

**Comment by SilviuMihai** [comment]
Oh yeah, in all the samples that are out there, should be a vote button, if people succeeded to make it work or used it in there projects. Thank you.
